### ISSUE TITLE
Target inside .dockerignore causing issues

### ISSUE THREAD

**Issue by jjdepaul** [mechero/spring-boot-hola-docker#1]
I was unable to build using the Dockerfile according to your instructions.   It kept complaining about missing JAR file.  It turned out that the .dockerignore file has this entry in it:  target/ - which essentially hides that JAR file and breaks the build.

**Comment by neklaf** [comment]
The same problem here, but a quick fix is just remove target line in .dockerignore file and the build is working perfectly

**Comment by mechero** [comment]
I'll fix it, thanks to both of you for reporting it 😄

**Comment by mechero** [comment]
Fixed!
